#!/bin/bash
# Script to push all local vimrc,ideavimrc,bashrc,custom commands to git repo
set -ex
cd /Users/pramod/Documents/workspace/config-docs/my-global-config
cp ~/.vimrc vimrc 
cp ~/.zshrc bashrc 
cp ~/.ideavimrc ideavimrc 
cp ~/custom-commands/* custom-commands 
cp ~/.vim/ftplugin/* vim

git checkout develop
git status
read -p "Do you wish to push(y/n)" ans 
if [[ $ans == "y" ]]
then
	git add .
	git status
	git commit -m "auto push"
	git push 
	echo "update & pushed"
else
	echo "Exiting gracefully"
fi
