#!/bin/bash
# Script to push all local vimrc,ideavimrc,bashrc,custom commands to git repo
set -ex

cd ~/Documents/workspace/config-docs/my-global-config

#copying shell/terminal config 
cp ~/.zshrc ./terminal/.zshrc

# copying vim config
cp ~/.vimrc ./vim/.vimrc
cp ~/.ideavimrc ./vim/.ideavimrc
cp ~/.vim/ftplugin/* ./vim/vim/

# copying nvim config
cp ~/.config/nvim/* ./nvim/.config/nvim/

# copying tmux config
cp ~/.tmux.conf ./tmux/.tmux.conf

# copying custom commands
cp ~/custom-commands/* ./custom-commands/ 

git checkout develop
git status
read -p "Do you wish to push(y/n)" ans 
if [[ $ans == "y" ]]
then
	git add .
	git status
	git commit -m "auto push"
	git push 
	echo "update & pushed"
else
	echo "Exiting gracefully"
fi
