require("pramod.plugins-setup") -- should be first
require("pramod.core.options")
require("pramod.core.keymaps")
require("pramod.core.colorscheme")
require("pramod.plugins.comment")
require("pramod.plugins.nvim-tree")
require("pramod.plugins.lualine")
require("pramod.plugins.telescope")
require("pramod.plugins.nvim-cmp")
require("pramod.plugins.lsp.mason")
require("pramod.plugins.lsp.lspsaga")
require("pramod.plugins.lsp.lspconfig")
require("pramod.plugins.lsp.null-ls")
require("pramod.plugins.autopairs")
require("pramod.plugins.treesitter")
require("pramod.plugins.gitsign")
