#!/usr/bin/env python3
#This script checks for json validations,provided json file is valid or not

import os
import sys
import json

if len(sys.argv) > 1:
    if os.path.exists(sys.argv[1]):
        file = open(sys.argv[1],"r")
        json.load(file)
        file.close()
        print("valid JSON")
    else:
        print(sys.argv[1] + " not found")
else:
    print("Usage: jsoncheck <file>")
